### ISSUE TITLE
DB 테이블 설계

### ISSUE THREAD

**Issue by lala9663** [FastcampusMini/mini-project#2]
## Title

DB 테이블 설계

## Description

- DB 테이블 설계
 - 회원 가입
 - 금융 상품
 - 장바구니
 - 로그아웃

## Tasks

- [x] 테이블 만들기

## References

임시 테이블이니 수정 필요

**Comment by superb-Jay** [comment]
임시 테이블 만든것 공유도 부탁드립니다.

**Comment by cutegyuseok** [comment]
@superb-Jay 임시테이블 관련해서는 탄력적 IP정보가 포함되어있어 discord 백엔드-대화 채널에 올라가있습니다
