### ISSUE TITLE
상품 구매 관련 Entity 및 Service, Repository 변경

### ISSUE THREAD

**Issue by cutegyuseok** [FastcampusMini/mini-project#37]
## Title

상품 구매 관련 Entity 및 Service, Repository 변경

## Description
중간 테이블을 사용한 관계가 아닌
Orders  (OneToMany) -> <- (ManyToOne) PurchaseProduct
1:N 양방향으로 변경

## Tasks

- [ ] Entity 수정
- [ ] Repository 수정
- [ ] Service 수정
- [ ] 새로운 DTO 생성

## References

- [참고 자료](https://tecoble.techcourse.co.kr/post/2021-08-15-jpa-cascadetype-remove-vs-orphanremoval-true/)

**Comment by cutegyuseok** [comment]
FetchType.EAGER 는 사용하지 않습니다.

**Comment by superb-Jay** [comment]
참고자료 정리 진짜 잘되어있네요 도움이 많이 되었어요.

**Comment by cutegyuseok** [comment]
구현은 완료 했는데 참 어렵네요 양방향 맵핑...하루종일 exception과 씨름했습니다
