### ISSUE TITLE
Auth Code 수정

### ISSUE THREAD

**Issue by cutegyuseok** [FastcampusMini/mini-project#47]
## Title

포스트맨 테스트중 수정해야 할것같은 부분 적어봅니다!

## Description
![image](https://user-images.githubusercontent.com/103543611/219771603-817f2181-2fd7-472e-b087-dc8d11a9ab9d.png)
@RequestBody
@AuthenticationPrincipal
이 두개 어노테이션을 같이 써버리면서 토큰은 못받고 json으로 받는 정보만 들어오는것 같아요!
토큰은 안받아도 되는거면 @AuthenticationPrincipal 은 빼도 괜찮지 않을까요...?

![image](https://user-images.githubusercontent.com/103543611/219772791-56dceb25-ddd1-4d9b-beb5-b1d98a0f64be.png)
@RequestBody 어노테이션을  토큰을 받아야 하는곳에 넣어버려서 요청이 꼬여버린것같아요...
아마
![image](https://user-images.githubusercontent.com/103543611/219773252-33a7e556-6b8f-4f49-a30a-1e1912b35070.png)
이걸 의도하신 거겠죠...?

![image](https://user-images.githubusercontent.com/103543611/219773564-5e5a2614-b260-4676-82fa-c1bf7f038597.png)
아무래도 여기도  @RequestBody 가 String password 앞에 있는걸 의도힌것같아요

## Tasks

- [x] /api/user
- [x] /api/user/update
- [x] /api/user/delete

## References

제가 재학님 의도를 정확히 이해하지 못한걸수도 있어서 이슈 남겨봅니다

**Comment by superb-Jay** [comment]
안그래도 이거땜에 지금 ..

**Comment by cutegyuseok** [comment]
파이팅입니다...이만 자러가겠습니다...

**Comment by superb-Jay** [comment]
완료.. 이제 스웨거로 테스트 하세요..
