### ISSUE TITLE
Json 관련..

### ISSUE THREAD

**Issue by superb-Jay** [FastcampusMini/mini-project#49]
## Title

스웨거에서 테스트가 안되는 이유를 알았습니다.

## Description

@ApiImplicitParams({
            @ApiImplicitParam(name = "basketId", value = "basketId", required = true),
    })

스웨거 어노테이션 해당 블록의 경우 폼로그인일 경우에만 테스트가 가능한것 같습니다.
해당 블록을 삭제하면 파라미터가 없다고 나오면 하단에 샘플로 json 데이터가 자동으로 입력됨을 알수 있었습니다.

폼 안에 글씨를 쓰려고 하면 자꾸 자동으로 지워지는것 또한 그때문인것으로 확인됩니다.

스웨거 너무 좋네요 앞으로 스웨거 씁시다 하하 #

**Comment by cutegyuseok** [comment]
그러면 저거 다 지워야겠네요...낼 할거생겼다...기쁘다....

**Comment by superb-Jay** [comment]
일단 로그인 사인업만 스웨거로 테스트 해보세요 생각보다 재밋습니다.. ㅋㅋ

**Comment by superb-Jay** [comment]
진짜 너무 열심히 찾아 해맷는데 우리 리포짓토리 프라이빗으로 바꾸고싶은 심정입니다 하하하하하

**Comment by cutegyuseok** [comment]
ㅋㅋㅋㅋㅋㅋㅋ하나 배워갑니다
