### ISSUE TITLE
cors 에러 관련

### ISSUE THREAD

**Issue by superb-Jay** [FastcampusMini/mini-project#50]
## Title

 CORS(Cross Origin Resource Sharing) 

프론트에서 백엔드서버로 api 요청을 보낼때 흔히 볼수 있는 에러들 중 하나 라고 합니다.
 
## Description

즉 보안상의 이유로, 웹 상에서는 다른 Origin으로 부터 요청 받는 리소스 접근을 제한하는 정책

예를 들어, 프론트엔드가 localhost:3000으로 개발 중인 상황에서, 백엔드 서버는 localhost:5000에서 호스팅 중인 상황이라면, 
이 둘은 서로 포트번호가 달라 다른 Origin으로 취급되어 SOP에 위반되게 되는 것이다. 이러한 상황을 우리가 흔히 말하는 CORS 에러라고 하는 것이다.

 Origin 이란 Protocol, Hostname, Port를 한데 묶은 것

![image](https://user-images.githubusercontent.com/113875954/219830673-fabba42f-000a-4062-a8a9-9cac5d5c7188.png)

## Tasks

- [x] controller마다 웹바인딩 어노테이션 추가
- [x] 스프링 시큐리티 필터체인 추가 및, cors 관련 빈 등록

## References

-[참고문서](https://velog.io/@seungchan__y/CORS-%EC%97%90%EB%9F%AC%EC%99%80-%ED%95%B4%EA%B2%B0%EB%B2%95)

**Comment by lala9663** [comment]
자세하게 써주셔서 보고 이해했습니다 감사합니다
